package sbp.com.sbt.dataspace.feather.modeldescriptioncommon;

import org.springframework.context.annotation.Bean;
import sbp.com.sbt.dataspace.feather.modeldescription.DataType;
import sbp.com.sbt.dataspace.feather.modeldescription.InheritanceStrategy;
import sbp.com.sbt.dataspace.feather.modeldescription.ModelDescription;
import sbp.com.sbt.dataspace.feather.modeldescription.TableType;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedHashSet;

class ModelDescriptionTestConfiguration {

    @Bean
    ModelDescription modelDescription() {
        return new ModelDescriptionImpl(new ModelDescriptionSettings()
                .setEnumDescriptionSettings("Status", new EnumDescriptionSettings()
                        .setValues(new LinkedHashSet<>(Arrays.asList("OPEN", "CLOSED"))))
                .setEnumDescriptionSettings("Attribute", new EnumDescriptionSettings()
                        .setValues(new LinkedHashSet<>(Arrays.asList("TOP_PRIORITY", "FORBIDDEN"))))
                .setEntityDescriptionSettings("TestEntity", new EntityDescriptionSettings()
                        .setAggregateEntityType("TestEntity")
                        .setFinal()
                        .setAggregate()
                        .setInheritanceStrategy(InheritanceStrategy.JOINED)
                        .setTableName("F_TEST_ENTITY")
                        .setIdColumnName("ID")
                        .setAggregateColumnName("AGGREGATE")
                        .setSystemLocksTableName("F_TEST_ENTITY_SYSTEM_LOCKS")
                        .setSystemLocksAggregateColumnName("AGGREGATE")
                        .setSystemLocksVersionColumnName("VERSION")
                        .setPrimitiveDescriptionSettings("code", new PrimitiveDescriptionSettings()
                                .setColumnName("CODE")
                                .setType(DataType.STRING)
                                .setMandatory())
                        .setPrimitiveDescriptionSettings("code_2", new PrimitiveDescriptionSettings()
                                .setColumnName("CODE")
                                .setType(DataType.STRING)
                                .setMandatory())
                        .setPrimitiveDescriptionSettings("p1", new PrimitiveDescriptionSettings()
                                .setColumnName("P1")
                                .setType(DataType.STRING))
                        .setPrimitiveDescriptionSettings("p2", new PrimitiveDescriptionSettings()
                                .setColumnName("P2")
                                .setType(DataType.BYTE))
                        .setPrimitiveDescriptionSettings("p3", new PrimitiveDescriptionSettings()
                                .setColumnName("P3")
                                .setType(DataType.SHORT))
                        .setPrimitiveDescriptionSettings("p4", new PrimitiveDescriptionSettings()
                                .setColumnName("P4")
                                .setType(DataType.INTEGER))
                        .setPrimitiveDescriptionSettings("p5", new PrimitiveDescriptionSettings()
                                .setColumnName("P5")
                                .setType(DataType.LONG))
                        .setPrimitiveDescriptionSettings("p6", new PrimitiveDescriptionSettings()
                                .setColumnName("P6")
                                .setType(DataType.DOUBLE))
                        .setPrimitiveDescriptionSettings("p7", new PrimitiveDescriptionSettings()
                                .setColumnName("P7")
                                .setType(DataType.DATETIME))
                        .setPrimitiveDescriptionSettings("p8", new PrimitiveDescriptionSettings()
                                .setColumnName("P8")
                                .setType(DataType.BOOLEAN))
                        .setPrimitiveDescriptionSettings("p9", new PrimitiveDescriptionSettings()
                                .setColumnName("P9")
                                .setType(DataType.BYTE_ARRAY))
                        .setPrimitiveDescriptionSettings("p10", new PrimitiveDescriptionSettings()
                                .setColumnName("P10")
                                .setType(DataType.BIG_DECIMAL))
                        .setPrimitiveDescriptionSettings("p11", new PrimitiveDescriptionSettings()
                                .setColumnName("P11")
                                .setType(DataType.TEXT))
                        .setPrimitiveDescriptionSettings("p12", new PrimitiveDescriptionSettings()
                                .setColumnName("P12")
                                .setType(DataType.FLOAT))
                        .setPrimitiveDescriptionSettings("p13", new PrimitiveDescriptionSettings()
                                .setColumnName("P13")
                                .setType(DataType.CHARACTER))
                        .setPrimitiveDescriptionSettings("p14", new PrimitiveDescriptionSettings()
                                .setColumnName("P14")
                                .setType(DataType.DATE))
                        .setPrimitiveDescriptionSettings("p15", new PrimitiveDescriptionSettings()
                                .setColumnName("P15")
                                .setType(DataType.OFFSET_DATETIME))
                        .setPrimitivesCollectionDescriptionSettings("ps1", new PrimitivesCollectionDescriptionSettings()
                                .setColumnName("ELEMENT")
                                .setTableName("F_TEST_ENTITY_PS1")
                                .setOwnerColumnName("OWNER")
                                .setType(DataType.STRING))
                        .setPrimitivesCollectionDescriptionSettings("ps2", new PrimitivesCollectionDescriptionSettings()
                                .setColumnName("ELEMENT")
                                .setTableName("F_TEST_ENTITY_PS2")
                                .setOwnerColumnName("OWNER")
                                .setType(DataType.INTEGER))
                        .setPrimitivesCollectionDescriptionSettings("ps3", new PrimitivesCollectionDescriptionSettings()
                                .setColumnName("ELEMENT")
                                .setTableName("F_TEST_ENTITY_PS3")
                                .setOwnerColumnName("OWNER")
                                .setType(DataType.DATETIME))
                        .setPrimitivesCollectionDescriptionSettings("ps4", new PrimitivesCollectionDescriptionSettings()
                                .setColumnName("ELEMENT")
                                .setTableName("F_TEST_ENTITY_PS4")
                                .setOwnerColumnName("OWNER")
                                .setType(DataType.BOOLEAN))
                        .setReferenceDescriptionSettings("r1", new ReferenceDescriptionSettings()
                                .setColumnName("R1")
                                .setEntityType("TestEntity")
                                .setEntityReferencesCollectionPropertyName("brec1"))
                        .setReferencesCollectionDescriptionSettings("rc1", new ReferencesCollectionDescriptionSettings()
                                .setColumnName("ELEMENT")
                                .setTableName("F_TEST_ENTITY_RC1")
                                .setOwnerColumnName("OWNER")
                                .setEntityType("TestEntity"))
                        .setGroupDescriptionSettings("g1", new GroupDescriptionSettings()
                                .setGroupName("Group1")
                                .setPrimitiveDescriptionSettings("p1", new PrimitiveDescriptionSettings()
                                        .setColumnName("G1_P1")
                                        .setType(DataType.STRING)))
                        .setGroupDescriptionSettings("g2", new GroupDescriptionSettings()
                                .setGroupName("Group2")
                                .setReferenceDescriptionSettings("r1", new ReferenceDescriptionSettings()
                                        .setColumnName("R1")
                                        .setEntityType("TestEntity")
                                        .setMandatory()))
                        .setGroupDescriptionSettings("g3", new GroupDescriptionSettings()
                                .setGroupName("Group3")
                                .setReferenceDescriptionSettings("r1", new ReferenceDescriptionSettings()
                                        .setColumnName("G3_R1")
                                        .setEntityType("Product"))))
                .setEntityDescriptionSettings("Entity", new EntityDescriptionSettings()
                        .setAggregate()
                        .setInheritanceStrategy(InheritanceStrategy.JOINED)
                        .setTableName("F_ENTITY")
                        .setIdColumnName("ID")
                        .setTypeColumnName("TYPE")
                        .setSystemLocksTableName("F_ENTITY_SYSTEM_LOCKS")
                        .setSystemLocksAggregateColumnName("AGGREGATE")
                        .setSystemLocksVersionColumnName("VERSION")
                        .setPrimitiveDescriptionSettings("code", new PrimitiveDescriptionSettings()
                                .setColumnName("CODE")
                                .setType(DataType.STRING)
                                .setMandatory())
                        .setPrimitiveDescriptionSettings("name", new PrimitiveDescriptionSettings()
                                .setColumnName("NAME")
                                .setType(DataType.STRING))
                        .setPrimitivesCollectionDescriptionSettings("attributes", new PrimitivesCollectionDescriptionSettings()
                                .setColumnName("ELEMENT")
                                .setTableName("F_ENTITY_ATTRIBUTES")
                                .setOwnerColumnName("OWNER")
                                .setType(DataType.STRING)
                                .setEnumType("Attribute")))
                .setEntityDescriptionSettings("Request", new EntityDescriptionSettings()
                        .setAggregateEntityType("Entity")
                        .setInheritanceStrategy(InheritanceStrategy.SINGLE_TABLE)
                        .setTableName("F_REQUEST")
                        .setIdColumnName("ID")
                        .setTypeColumnName("TYPE")
                        .setAggregateColumnName("AGGREGATE")
                        .setPrimitiveDescriptionSettings("code", new PrimitiveDescriptionSettings()
                                .setColumnName("CODE")
                                .setType(DataType.STRING)
                                .setMandatory())
                        .setReferenceDescriptionSettings("createdEntity", new ReferenceDescriptionSettings()
                                .setColumnName("CREATED_ENTITY")
                                .setEntityType("Entity")
                                .setEntityReferencePropertyName("request"))
                        .setReferenceDescriptionSettings("agreement", new ReferenceDescriptionSettings()
                                .setColumnName("AGREEMENT")
                                .setEntityType("Agreement")
                                .setEntityReferencePropertyName("request"))
                        .setGroupDescriptionSettings("initiator", new GroupDescriptionSettings()
                                .setGroupName("Person")
                                .setPrimitiveDescriptionSettings("firstName", new PrimitiveDescriptionSettings()
                                        .setColumnName("INITIATOR_FIRST_NAME")
                                        .setType(DataType.STRING)
                                        .setMandatory())
                                .setPrimitiveDescriptionSettings("lastName", new PrimitiveDescriptionSettings()
                                        .setColumnName("INITIATOR_LAST_NAME")
                                        .setType(DataType.STRING))
                                .setPrimitiveDescriptionSettings("age", new PrimitiveDescriptionSettings()
                                        .setColumnName("INITIATOR_AGE")
                                        .setType(DataType.INTEGER))
                                .setReferenceDescriptionSettings("document", new ReferenceDescriptionSettings()
                                        .setColumnName("INITIATOR_DOCUMENT")
                                        .setEntityType("Document"))))
                .setEntityDescriptionSettings("RequestPlus", new EntityDescriptionSettings()
                        .setParentEntityType("Request")
                        .setPrimitiveDescriptionSettings("description", new PrimitiveDescriptionSettings()
                                .setColumnName("DESCRIPTION")
                                .setType(DataType.STRING)))
                .setEntityDescriptionSettings("RequestSpecial", new EntityDescriptionSettings()
                        .setParentEntityType("Request")
                        .setPrimitiveDescriptionSettings("specialCode", new PrimitiveDescriptionSettings()
                                .setColumnName("SPECIAL_CODE")
                                .setType(DataType.STRING)))
                .setEntityDescriptionSettings("Parameter", new EntityDescriptionSettings()
                        .setParentEntityType("Entity")
                        .setTableName("F_PARAMETER")
                        .setIdColumnName("ID")
                        .setPrimitiveDescriptionSettings("value", new PrimitiveDescriptionSettings()
                                .setColumnName("VALUE")
                                .setType(DataType.STRING))
                        .setReferenceDescriptionSettings("entity", new ReferenceDescriptionSettings()
                                .setColumnName("ENTITY")
                                .setEntityType("Entity")
                                .setMandatory()
                                .setEntityReferencesCollectionPropertyName("parameters")))
                .setEntityDescriptionSettings("ActionParameter", new EntityDescriptionSettings()
                        .setParentEntityType("Parameter")
                        .setTableName("F_ACTION_PARAMETER")
                        .setIdColumnName("ID")
                        .setPrimitiveDescriptionSettings("executorName", new PrimitiveDescriptionSettings()
                                .setColumnName("EXECUTOR_NAME")
                                .setType(DataType.STRING)))
                .setEntityDescriptionSettings("ActionParameterSpecial", new EntityDescriptionSettings()
                        .setParentEntityType("ActionParameter")
                        .setTableName("F_ACTION_PARAMETER_SPECIAL")
                        .setIdColumnName("ID")
                        .setPrimitiveDescriptionSettings("specialOffer", new PrimitiveDescriptionSettings()
                                .setColumnName("SPECIAL_OFFER")
                                .setType(DataType.STRING)))
                .setEntityDescriptionSettings("Service", new EntityDescriptionSettings()
                        .setParentEntityType("Entity")
                        .setTableName("F_SERVICE")
                        .setIdColumnName("ID")
                        .setPrimitiveDescriptionSettings("managerPersonalCode", new PrimitiveDescriptionSettings()
                                .setColumnName("MANAGER_PERSONAL_CODE")
                                .setType(DataType.INTEGER))
                        .setReferenceDescriptionSettings("startAction", new ReferenceDescriptionSettings()
                                .setColumnName("START_ACTION")
                                .setEntityType("Action"))
                        .setGroupDescriptionSettings("initiator", new GroupDescriptionSettings()
                                .setGroupName("Person")
                                .setPrimitiveDescriptionSettings("firstName", new PrimitiveDescriptionSettings()
                                        .setColumnName("INITIATOR_FIRST_NAME")
                                        .setType(DataType.STRING)
                                        .setMandatory())
                                .setPrimitiveDescriptionSettings("lastName", new PrimitiveDescriptionSettings()
                                        .setColumnName("INITIATOR_LAST_NAME")
                                        .setType(DataType.STRING))
                                .setPrimitiveDescriptionSettings("age", new PrimitiveDescriptionSettings()
                                        .setColumnName("INITIATOR_AGE")
                                        .setType(DataType.INTEGER))
                                .setReferenceDescriptionSettings("document", new ReferenceDescriptionSettings()
                                        .setColumnName("INITIATOR_DOCUMENT")
                                        .setEntityType("Document"))))
                .setEntityDescriptionSettings("Operation", new EntityDescriptionSettings()
                        .setParentEntityType("Entity")
                        .setTableName("F_OPERATION")
                        .setIdColumnName("ID")
                        .setReferenceDescriptionSettings("service", new ReferenceDescriptionSettings()
                                .setColumnName("SERVICE")
                                .setEntityType("Service")
                                .setEntityReferencesCollectionPropertyName("operations")))
                .setEntityDescriptionSettings("OperationSpecial", new EntityDescriptionSettings()
                        .setParentEntityType("Operation")
                        .setTableName("F_OPERATION_SPECIAL")
                        .setIdColumnName("ID")
                        .setPrimitiveDescriptionSettings("specialOffer", new PrimitiveDescriptionSettings()
                                .setColumnName("SPECIAL_OFFER")
                                .setType(DataType.STRING))
                        .setReferenceDescriptionSettings("product", new ReferenceDescriptionSettings()
                                .setEntityType("Product")
                                .setColumnName("PRODUCT"))
                        .setGroupDescriptionSettings("initiator", new GroupDescriptionSettings()
                                .setGroupName("Person")
                                .setPrimitiveDescriptionSettings("firstName", new PrimitiveDescriptionSettings()
                                        .setColumnName("INITIATOR_FIRST_NAME")
                                        .setType(DataType.STRING)
                                        .setMandatory())
                                .setPrimitiveDescriptionSettings("lastName", new PrimitiveDescriptionSettings()
                                        .setColumnName("INITIATOR_LAST_NAME")
                                        .setType(DataType.STRING))
                                .setPrimitiveDescriptionSettings("age", new PrimitiveDescriptionSettings()
                                        .setColumnName("INITIATOR_AGE")
                                        .setType(DataType.INTEGER))
                                .setReferenceDescriptionSettings("document", new ReferenceDescriptionSettings()
                                        .setColumnName("INITIATOR_DOCUMENT")
                                        .setEntityType("Document"))))
                .setEntityDescriptionSettings("OperationLimited", new EntityDescriptionSettings()
                        .setParentEntityType("Operation")
                        .setTableName("F_OPERATION_LIMITED")
                        .setIdColumnName("ID")
                        .setPrimitiveDescriptionSettings("limitedOffer", new PrimitiveDescriptionSettings()
                                .setColumnName("LIMITED_OFFER")
                                .setType(DataType.STRING))
                        .setPrimitiveDescriptionSettings("endDate", new PrimitiveDescriptionSettings()
                                .setColumnName("END_DATE")
                                .setType(DataType.DATETIME))
                        .setReferenceDescriptionSettings("product", new ReferenceDescriptionSettings()
                                .setEntityType("Product")
                                .setColumnName("PRODUCT")))
                .setEntityDescriptionSettings("Action", new EntityDescriptionSettings()
                        .setParentEntityType("Entity")
                        .setTableName("F_ACTION")
                        .setIdColumnName("ID")
                        .setPrimitiveDescriptionSettings("algorithmCode", new PrimitiveDescriptionSettings()
                                .setColumnName("ALGORITHM_CODE")
                                .setType(DataType.INTEGER))
                        .setReferenceDescriptionSettings("operation", new ReferenceDescriptionSettings()
                                .setColumnName("OPERATION")
                                .setEntityType("Operation")
                                .setEntityReferencesCollectionPropertyName("actions")))
                .setEntityDescriptionSettings("ActionSpecial", new EntityDescriptionSettings()
                        .setParentEntityType("Action")
                        .setTableName("F_ACTION_SPECIAL")
                        .setIdColumnName("ID")
                        .setPrimitiveDescriptionSettings("specialOffer", new PrimitiveDescriptionSettings()
                                .setColumnName("SPECIAL_OFFER")
                                .setType(DataType.STRING)))
                .setEntityDescriptionSettings("Event", new EntityDescriptionSettings()
                        .setParentEntityType("Entity")
                        .setTableName("F_EVENT")
                        .setIdColumnName("ID")
                        .setPrimitiveDescriptionSettings("author", new PrimitiveDescriptionSettings()
                                .setColumnName("AUTHOR")
                                .setType(DataType.STRING)))
                .setEntityDescriptionSettings("Product", new EntityDescriptionSettings()
                        .setParentEntityType("Entity")
                        .setTableName("F_PRODUCT")
                        .setIdColumnName("ID")
                        .setPrimitiveDescriptionSettings("creatorCode", new PrimitiveDescriptionSettings()
                                .setColumnName("CREATOR_CODE")
                                .setType(DataType.INTEGER))
                        .setPrimitivesCollectionDescriptionSettings("aliases", new PrimitivesCollectionDescriptionSettings()
                                .setColumnName("ELEMENT")
                                .setTableName("F_PRODUCT_ALIASES")
                                .setOwnerColumnName("OWNER")
                                .setType(DataType.STRING))
                        .setPrimitivesCollectionDescriptionSettings("rates", new PrimitivesCollectionDescriptionSettings()
                                .setColumnName("ELEMENT")
                                .setTableName("F_PRODUCT_RATES")
                                .setOwnerColumnName("OWNER")
                                .setType(DataType.DOUBLE))
                        .setReferenceDescriptionSettings("relatedProduct", new ReferenceDescriptionSettings()
                                .setColumnName("RELATED_PRODUCT")
                                .setEntityType("Product"))
                        .setReferenceDescriptionSettings("mainDocument", new ReferenceDescriptionSettings()
                                .setColumnName("MAIN_DOCUMENT")
                                .setEntityType("Document"))
                        .setReferencesCollectionDescriptionSettings("services", new ReferencesCollectionDescriptionSettings()
                                .setColumnName("ELEMENT")
                                .setTableName("F_PRODUCT_SERVICES")
                                .setOwnerColumnName("OWNER")
                                .setEntityType("Service"))
                        .setReferencesCollectionDescriptionSettings("events", new ReferencesCollectionDescriptionSettings()
                                .setColumnName("ELEMENT")
                                .setTableName("F_PRODUCT_EVENTS")
                                .setOwnerColumnName("OWNER")
                                .setEntityType("Event")))
                .setEntityDescriptionSettings("ProductPlus", new EntityDescriptionSettings()
                        .setParentEntityType("Product")
                        .setTableName("F_PRODUCT_PLUS")
                        .setIdColumnName("ID")
                        .setReferencesCollectionDescriptionSettings("affectedProducts", new ReferencesCollectionDescriptionSettings()
                                .setColumnName("ELEMENT")
                                .setTableName("F_PRODUCT_PLUS_AFFECTED_PRODUCTS")
                                .setOwnerColumnName("OWNER")
                                .setEntityType("Product")))
                .setEntityDescriptionSettings("ProductLimited", new EntityDescriptionSettings()
                        .setParentEntityType("ProductPlus")
                        .setTableName("F_PRODUCT_LIMITED")
                        .setIdColumnName("ID")
                        .setPrimitiveDescriptionSettings("limitedOffer", new PrimitiveDescriptionSettings()
                                .setColumnName("LIMITED_OFFER")
                                .setType(DataType.STRING)))
                .setEntityDescriptionSettings("Document", new EntityDescriptionSettings()
                        .setInheritanceStrategy(InheritanceStrategy.SINGLE_TABLE)
                        .setTableName("F_DOCUMENT")
                        .setIdColumnName("ID")
                        .setTypeColumnName("TYPE")
                        .setPrimitiveDescriptionSettings("code", new PrimitiveDescriptionSettings()
                                .setColumnName("CODE")
                                .setType(DataType.STRING)
                                .setMandatory())
                        .setPrimitiveDescriptionSettings("status", new PrimitiveDescriptionSettings()
                                .setColumnName("STATUS")
                                .setType(DataType.STRING)
                                .setEnumType("Status"))
                        .setReferenceDescriptionSettings("product", new ReferenceDescriptionSettings()
                                .setColumnName("PRODUCT")
                                .setEntityType("Product")
                                .setEntityReferencesCollectionPropertyName("documents")))
                .setEntityDescriptionSettings("Permission", new EntityDescriptionSettings()
                        .setParentEntityType("Document")
                        .setPrimitiveDescriptionSettings("number", new PrimitiveDescriptionSettings()
                                .setColumnName("NUMBER_")
                                .setType(DataType.INTEGER)))
                .setEntityDescriptionSettings("Agreement", new EntityDescriptionSettings()
                        .setParentEntityType("Document")
                        .setPrimitiveDescriptionSettings("participant", new PrimitiveDescriptionSettings()
                                .setColumnName("PARTICIPANT")
                                .setType(DataType.STRING))
                        .setReferenceDescriptionSettings("document", new ReferenceDescriptionSettings()
                                .setColumnName("DOCUMENT")
                                .setEntityType("Document")
                                .setEntityReferencesCollectionPropertyName("agreements")))
                .setEntityDescriptionSettings("AgreementSpecial", new EntityDescriptionSettings()
                        .setParentEntityType("Agreement")
                        .setPrimitiveDescriptionSettings("specialConditions", new PrimitiveDescriptionSettings()
                                .setColumnName("SPECIAL_CONDITIONS")
                                .setType(DataType.STRING)))
                .setEntityDescriptionSettings("UserProduct", new EntityDescriptionSettings()
                        .setFinal()
                        .setInheritanceStrategy(InheritanceStrategy.JOINED)
                        .setTableType(TableType.QUERY)
                        .setIdColumnName("ID")
                        .setParamDescriptionSettings("firstName", new ParamDescriptionSettings()
                                .setType(DataType.STRING))
                        .setParamDescriptionSettings("lastName", new ParamDescriptionSettings()
                                .setType(DataType.STRING))
                        .setPrimitiveDescriptionSettings("code", new PrimitiveDescriptionSettings()
                                .setColumnName("CODE")
                                .setType(DataType.STRING)
                                .setMandatory())
                        .setPrimitivesCollectionDescriptionSettings("aliases", new PrimitivesCollectionDescriptionSettings()
                                .setColumnName("ELEMENT")
                                .setTableName("F_PRODUCT_ALIASES")
                                .setOwnerColumnName("OWNER")
                                .setType(DataType.STRING))
                        .setReferenceDescriptionSettings("relatedProduct", new ReferenceDescriptionSettings()
                                .setColumnName("RELATED_PRODUCT")
                                .setEntityType("Product"))
                        .setReferencesCollectionDescriptionSettings("services", new ReferencesCollectionDescriptionSettings()
                                .setColumnName("ELEMENT")
                                .setTableName("F_PRODUCT_SERVICES")
                                .setOwnerColumnName("OWNER")
                                .setEntityType("Service"))
                        .setGroupDescriptionSettings("initiator", new GroupDescriptionSettings()
                                .setGroupName("Person")
                                .setPrimitiveDescriptionSettings("firstName", new PrimitiveDescriptionSettings()
                                        .setColumnName("INITIATOR_FIRST_NAME")
                                        .setType(DataType.STRING)
                                        .setMandatory())
                                .setPrimitiveDescriptionSettings("lastName", new PrimitiveDescriptionSettings()
                                        .setColumnName("INITIATOR_LAST_NAME")
                                        .setType(DataType.STRING))
                                .setPrimitiveDescriptionSettings("age", new PrimitiveDescriptionSettings()
                                        .setColumnName("INITIATOR_AGE")
                                        .setType(DataType.INTEGER))
                                .setReferenceDescriptionSettings("document", new ReferenceDescriptionSettings()
                                        .setColumnName("INITIATOR_DOCUMENT")
                                        .setEntityType("Document"))))
                .setEntityDescriptionSettings("ProductCopy", new EntityDescriptionSettings()
                        .setFinal()
                        .setInheritanceStrategy(InheritanceStrategy.JOINED)
                        .setTableType(TableType.QUERY)
                        .setPrimitiveDescriptionSettings("idCopy", new PrimitiveDescriptionSettings()
                                .setColumnName("ID")
                                .setType(DataType.STRING)
                                .setMandatory()))
                .setEntityDescriptionSettings("Test2Entity", new EntityDescriptionSettings()
                        .setFinal()
                        .setInheritanceStrategy(InheritanceStrategy.JOINED)
                        .setTableType(TableType.QUERY)
                        .setIdColumnName("ID")
                        .setParamDescriptionSettings("character", new ParamDescriptionSettings()
                                .setType(DataType.CHARACTER)
                                .setDefaultValue('a'))
                        .setParamDescriptionSettings("string", new ParamDescriptionSettings()
                                .setType(DataType.STRING)
                                .setDefaultValue("Test"))
                        .setParamDescriptionSettings("byte", new ParamDescriptionSettings()
                                .setType(DataType.BYTE)
                                .setDefaultValue((byte) 1))
                        .setParamDescriptionSettings("short", new ParamDescriptionSettings()
                                .setType(DataType.SHORT)
                                .setDefaultValue((short) 1))
                        .setParamDescriptionSettings("integer", new ParamDescriptionSettings()
                                .setType(DataType.INTEGER)
                                .setDefaultValue(1))
                        .setParamDescriptionSettings("long", new ParamDescriptionSettings()
                                .setType(DataType.LONG)
                                .setDefaultValue(1L))
                        .setParamDescriptionSettings("float", new ParamDescriptionSettings()
                                .setType(DataType.FLOAT)
                                .setDefaultValue(1.1f))
                        .setParamDescriptionSettings("double", new ParamDescriptionSettings()
                                .setType(DataType.DOUBLE)
                                .setDefaultValue(1.1))
                        .setParamDescriptionSettings("bigDecimal", new ParamDescriptionSettings()
                                .setType(DataType.BIG_DECIMAL)
                                .setDefaultValue(new BigDecimal("1.1")))
                        .setParamDescriptionSettings("date", new ParamDescriptionSettings()
                                .setType(DataType.DATE)
                                .setDefaultValue(LocalDate.of(2022, 6, 27)))
                        .setParamDescriptionSettings("datetime", new ParamDescriptionSettings()
                                .setType(DataType.DATETIME)
                                .setDefaultValue(LocalDateTime.of(2022, 6, 27, 14, 58, 10, 123000000)))
                        .setParamDescriptionSettings("offsetDatetime", new ParamDescriptionSettings()
                                .setType(DataType.OFFSET_DATETIME)
                                .setDefaultValue(OffsetDateTime.of(2022, 6, 27, 14, 58, 10, 123000000, ZoneOffset.of("+06:00"))))
                        .setParamDescriptionSettings("boolean", new ParamDescriptionSettings()
                                .setType(DataType.BOOLEAN)
                                .setDefaultValue(true))
                        .setParamDescriptionSettings("strings", new ParamDescriptionSettings()
                                .setType(DataType.STRING)
                                .setCollection()))
                .setEntityDescriptionSettings("Test3Entity", new EntityDescriptionSettings()
                        .setFinal()
                        .setInheritanceStrategy(InheritanceStrategy.JOINED)
                        .setTableType(TableType.QUERY)
                        .setIdColumnName("ID"))
                .setEntityDescriptionSettings("EntityA", new EntityDescriptionSettings()
                        .setInheritanceStrategy(InheritanceStrategy.JOINED)
                        .setTableName("F_ENTITY_A")
                        .setIdColumnName("ID")
                        .setTypeColumnName("TYPE")
                        .setPrimitiveDescriptionSettings("code", new PrimitiveDescriptionSettings()
                                .setColumnName("CODE")
                                .setType(DataType.STRING)
                                .setMandatory())
                        .setReferenceDescriptionSettings("refB", new ReferenceDescriptionSettings()
                                .setColumnName("REF_B")
                                .setEntityType("EntityB")
                                .setMandatory()
                                .setEntityReferencesCollectionPropertyName("refsA"))
                        .setReferenceDescriptionSettings("ref2B", new ReferenceDescriptionSettings()
                                .setColumnName("REF2_B")
                                .setEntityType("EntityB")
                                .setMandatory()))
                .setEntityDescriptionSettings("EntityAA", new EntityDescriptionSettings()
                        .setParentEntityType("EntityA")
                        .setTableName("F_ENTITY_AA")
                        .setIdColumnName("ID")
                        .setPrimitiveDescriptionSettings("codeAA", new PrimitiveDescriptionSettings()
                                .setColumnName("CODE_AA")
                                .setType(DataType.STRING)))
                .setEntityDescriptionSettings("EntityAAA", new EntityDescriptionSettings()
                        .setParentEntityType("EntityAA")
                        .setTableName("F_ENTITY_AAA")
                        .setIdColumnName("ID")
                        .setPrimitiveDescriptionSettings("codeAAA", new PrimitiveDescriptionSettings()
                                .setColumnName("CODE_AAA")
                                .setType(DataType.STRING))
                        .setReferenceDescriptionSettings("refE", new ReferenceDescriptionSettings()
                                .setColumnName("REF_E")
                                .setEntityType("EntityE")))
                .setEntityDescriptionSettings("EntityB", new EntityDescriptionSettings()
                        .setInheritanceStrategy(InheritanceStrategy.JOINED)
                        .setTableName("F_ENTITY_B")
                        .setIdColumnName("ID")
                        .setTypeColumnName("TYPE")
                        .setPrimitiveDescriptionSettings("code", new PrimitiveDescriptionSettings()
                                .setColumnName("CODE")
                                .setType(DataType.STRING)
                                .setMandatory())
                        .setReferenceDescriptionSettings("refC", new ReferenceDescriptionSettings()
                                .setColumnName("REF_C")
                                .setEntityType("EntityC")
                                .setMandatory()))
                .setEntityDescriptionSettings("EntityC", new EntityDescriptionSettings()
                        .setInheritanceStrategy(InheritanceStrategy.JOINED)
                        .setTableName("F_ENTITY_C")
                        .setIdColumnName("ID")
                        .setTypeColumnName("TYPE")
                        .setPrimitiveDescriptionSettings("code", new PrimitiveDescriptionSettings()
                                .setColumnName("CODE")
                                .setType(DataType.STRING)
                                .setMandatory())
                        .setReferenceDescriptionSettings("refD", new ReferenceDescriptionSettings()
                                .setColumnName("REF_D")
                                .setEntityType("EntityD")))
                .setEntityDescriptionSettings("EntityD", new EntityDescriptionSettings()
                        .setInheritanceStrategy(InheritanceStrategy.JOINED)
                        .setTableName("F_ENTITY_D")
                        .setIdColumnName("ID")
                        .setTypeColumnName("TYPE")
                        .setPrimitiveDescriptionSettings("code", new PrimitiveDescriptionSettings()
                                .setColumnName("CODE")
                                .setType(DataType.STRING)
                                .setMandatory())
                        .setReferenceDescriptionSettings("refE", new ReferenceDescriptionSettings()
                                .setColumnName("REF_E")
                                .setEntityType("EntityE")
                                .setMandatory()))
                .setEntityDescriptionSettings("EntityE", new EntityDescriptionSettings()
                        .setInheritanceStrategy(InheritanceStrategy.JOINED)
                        .setTableName("F_ENTITY_E")
                        .setIdColumnName("ID")
                        .setTypeColumnName("TYPE")
                        .setPrimitiveDescriptionSettings("code", new PrimitiveDescriptionSettings()
                                .setColumnName("CODE")
                                .setType(DataType.STRING)
                                .setMandatory())),
                Collections.singletonList(new TestModelDescriptionCheck()));
    }
}
