package sbp.com.sbt.dataspace.feather.testentitiesreadaccessjson;

import sbp.com.sbt.dataspace.feather.testcommon.TestData;

import java.util.Arrays;
import java.util.List;

import static sbp.com.sbt.dataspace.feather.testcommon.TestData.testData;

/**
 * Case with exception 1<ul>
 * <li>Incorrect JSON</li>
 * <li>Unexpected field</li>
 * <li>Свойство не найдено</li>
 * <li>Unexpected sorting order</li>
 * <li>Extra fields with zero limitation of elements quantity</li>
 * <li>Ineffective search</li>
 * <li>Incorrect node type</li>
 * <li>Не задан тип</li>
 * <li>Incorrect addressing to the collection element</li>
 * <li>The grouping specification is not set</li>
 * <li>The sorting criterion is not set</li>
 * <li>Incorrect type</li>
 * <li>Unsupported operation</li>
 * <li>The entity type is not an aggregate</li>
 * <li>Alias duplicates</li>
 * <li>Extra fields during merge requests</li>
 * <li>Insufficient number of requests for merging</li>
 * <li>Property type conflict</li>
 * <li>Extra fields when selecting properties</li>
 * <li>The node is not a symbol</li>
 * <li>The parameter value is not set</li>
 * <li>A null value is set for the parameter collection</li>
 * </ul>
 */
class ExceptionCase1 extends ExceptionCase {

    @Override
    void createEntities() {
        // Никаких действий не требуется
    }

    @Override
    List<TestData> getTestsData() {
        return Arrays.asList(
            testData("Incorrect JSON", "incorrectjson"),
            testData("Incorrect JSON (2)", "incorrectJson2"),
            testData("Incorrect JSON (3)", "incorrectJson3"),
            testData("Unexpected field", "unexpected_field"),
            testData("Property not found", "propertyNotFound"),
            testData("Property not found (2)", "propertyNotFound2"),
            testData("Unexpected sort order", "unexpectedSortOrder"),
            testData("Redundant fields with zero limit restriction", "extraFieldsForZeroLimit"),
            testData("Inefficient search", "ineffectiveSearch"),
            testData("Incorrect node type", "incorrectNodeType"),
            testData("Incorrect node type (2)", "incorrectNodeType2"),
            testData("Incorrect node type (3)", "incorrectNodeType3"),
            testData("Incorrect node type (4)", "incorrectNodeType4"),
            testData("Incorrect node type (5)", "incorrectNodeType5"),
            testData("Incorrect node type (6)", "incorrectNodeType6"),
            testData("Incorrect node type (7)", "incorrectNodeType7"),
            testData("Incorrect node type (8)", "incorrectNodeType8"),
            testData("Incorrect node type (9)", "incorrectNodeType9"),
            testData("Incorrect node type (10)", "incorrectNodeType10"),
            testData("Incorrect node type (11)", "incorrectNodeType(11)"),
            testData("Incorrect node type (12)", "incorrectNodeType12"),
            testData("Incorrect node type (13)", "incorrectNodeType13"),
            testData("Incorrect node type (14)", "incorrectNodeType14"),
            testData("Incorrect node type (15)", "incorrectNodeType15"),
            testData("Incorrect node type (16)", "incorrectNodeType16"),
            testData("Incorrect node type (17)", "incorrectNodeType17"),
            testData("Type not specified", "typeNotSet"),
            testData("Incorrect addressing to collection element", "incorrectCollectionElementAddressing"),
            testData("The grouping specification is not set", "groupSpecificationNotSet"),
            testData("The sorting criterion is not set", "sortCriterionNotSet"),
            testData("Incorrect type", "incorrectType"),
            testData("Unsupported operation", "unsupportedOperation"),
            testData("Unsupported operation (2)", "unsupportedOperation2"),
            testData("Unsupported operation (3)", "unsupportedOperation3"),
            testData("Unsupported operation (4)", "unsupportedOperation4"),
            testData("Unsupported operation (5)", "unsupportedOperation5"),
            testData("Unsupported operation (6)", "unsupportedOperation6"),
            testData("Unsupported operation (7)", "unsupportedOperation7"),
            testData("Unsupported operation (8)", "unsupportedOperation8"),
            testData("Unsupported operation (9)", "unsupportedOperation9"),
            testData("Unsupported operation (10)", "unsupportedOperation10"),
            testData("Unsupported operation (11)", "unsupportedOperation11"),
            testData("Unsupported operation (12)", "unsupportedOperation12"),
            testData("Unsupported operation (13)", "unsupportedOperation13"),
            testData("Unsupported operation (14)", "unsupportedOperation14"),
            testData("Unsupported operation (15)", "unsupportedOperation15"),
            testData("Unsupported operation (16)", "unsupportedOperation16"),
            testData("Unsupported operation (17)", "unsupportedOperation17"),
            testData("Unsupported operation (18)", "unsupportedOperation18"),
            testData("Unsupported operation (19)", "unsupportedOperation19"),
            testData("Unsupported operation (20)", "unsupportedOperation20"),
            testData("Unsupported operation (21)", "unsupportedOperation21"),
            testData("Unsupported operation (22)", "unsupportedOperation22"),
            testData("Unsupported operation (23)", "unsupportedOperation23"),
            testData("Unsupported operation (24)", "unsupportedOperation2024"),
            testData("Unsupported operation (25)", "unsupportedOperation25"),
            testData("Unsupported operation (26)", "unsupportedOperation26"),
            testData("Unsupported operation (27)", "unsupportedOperation27"),
            testData("Unsupported operation (28)", "unsupportedOperation28"),
            testData("Unsupported operation (29)", "unsupportedOperation29"),
            testData("Unsupported operation (30)", "unsupportedOperation30"),
            testData("Unsupported operation (31)", "unsupportedOperation31"),
            testData("Unsupported operation (32)", "unsupportedOperation32"),
            testData("Unsupported operation (33)", "unsupportedOperation33"),
            testData("Unsupported operation (34)", "unsupportedOperation34"),
            testData("Unsupported operation (35)", "unsupportedOperation35"),
            testData("Unsupported operation (36)", "unsupportedOperation36"),
            testData("Unsupported operation (37)", "unsupportedOperation37"),
            testData("Unsupported operation (38)", "unsupportedOperation38"),
            testData("Unsupported operation (39)", "unsupportedOperation39"),
            testData("Unsupported operation (40)", "unsupportedOperation40"),
            testData("Unsupported operation (41)", "unsupportedOperation41"),
            testData("Unsupported operation (42)", "unsupportedOperation42"),
            testData("Unsupported operation (43)", "unsupportedOperation43"),
            testData("Unsupported operation (44)", "unsupportedOperation44"),
            testData("Unsupported operation (45)", "unsupportedOperation45"),
            testData("Unsupported operation (46)", "unsupportedOperation46"),
            testData("Unsupported operation (47)", "unsupportedOperation47"),
            testData("Unsupported operation (48)", "unsupportedOperation48"),
            testData("Unsupported operation (49)", "unsupportedOperation49"),
            testData("Unsupported operation (50)", "unsupportedOperation50"),
            testData("Unsupported operation (51)", "unsupportedOperation51"),
            testData("Unsupported operation (52)", "unsupportedOperation52"),
            testData("Unsupported operation (53)", "unsupportedOperation53"),
            testData("Unsupported operation (54)", "unsupportedOperation54"),
            testData("Unsupported operation (55)", "unsupportedOperation55"),
            testData("Unsupported operation (56)", "unsupportedOperation56"),
            testData("Unsupported operation (57)", "unsupportedOperation57"),
            testData("Unsupported operation (58)", "unsupportedOperation58"),
            testData("Unsupported operation (59)", "unsupportedOperation59"),
            testData("Unsupported operation (60)", "unsupportedOperation60"),
            testData("Unsupported operation (61)", "unsupportedOperation61"),
            testData("Unsupported operation (62)", "unsupportedOperation62"),
            testData("Unsupported operation (63)", "unsupportedOperation63"),
            testData("Unsupported operation (64)", "unsupportedOperation64"),
            testData("Unsupported operation (65)", "unsupportedOperation65"),
            testData("Unsupported operation (66)", "unsupportedOperation66"),
            testData("Unsupported operation (67)", "unsupportedOperation67"),
            testData("Unsupported operation (68)", "unsupportedOperation68"),
            testData("Unsupported operation (69)", "unsupportedOperation69"),
            testData("Unsupported operation (70)", "unsupportedOperation70"),
            testData("Unsupported operation (71)", "unsupportedOperation71"),
            testData("Unsupported operation (72)", "unsupportedOperation72"),
            testData("Unsupported operation (73)", "unsupportedOperation73"),
            testData("Unsupported operation (74)", "unsupportedOperation74"),
            testData("Unsupported operation (75)", "unsupportedOperation75"),
            testData("Unsupported operation (76)", "unsupportedOperation76"),
            testData("Unsupported operation (77)", "unsupportedOperation77"),
            testData("Unsupported operation (78)", "unsupportedOperation78"),
            testData("Unsupported operation (79)", "unsupportedOperation79"),
            testData("Unsupported operation (80)", "unsupportedOperation80"),
            testData("Unsupported operation (81)", "unsupportedOperation81"),
            testData("Unsupported operation (82)", "unsupportedOperation82"),
            testData("Unsupported operation (83)", "unsupportedOperation83"),
            testData("Unsupported operation (84)", "unsupportedOperation84"),
            testData("Unsupported operation (85)", "unsupportedOperation85"),
            testData("Unsupported operation (86)", "unsupportedOperation86"),
            testData("Unsupported operation (87)", "unsupportedOperation87"),
            testData("Unsupported operation (88)", "unsupportedOperation88"),
            testData("Unsupported operation (89)", "unsupportedOperation89"),
            testData("Unsupported operation (90)", "unsupportedOperation90"),
            testData("Unsupported operation (91)", "unsupportedOperation91"),
            testData("Unsupported operation (92)", "unsupportedOperation92"),
            testData("Unsupported operation (93)", "unsupportedOperation93"),
            testData("Unsupported operation (94)", "unsupportedOperation94"),
            testData("Unsupported operation (95)", "unsupportedOperation95"),
            testData("Unsupported operation (96)", "unsupportedOperation96"),
            testData("Unsupported operation (97)", "unsupportedOperation97"),
            testData("Unsupported operation (98)", "unsupportedOperation98"),
            testData("Unsupported operation (99)", "unsupportedoperation99"),
            testData("Unsupported operation (100)", "unsupportedOperation100"),
            testData("Unsupported operation (101)", "unsupportedOperation101"),
            testData("Unsupported operation (102)", "unsupportedOperation102"),
            testData("Unsupported operation (103)", "unsupportedOperation103"),
            testData("Unsupported operation (104)", "unsupportedOperation104"),
            testData("Unsupported operation (105)", "unsupportedOperation105"),
            testData("Unsupported operation (106)", "unsupportedOperation106"),
            testData("Unsupported operation (107)", "unsupportedOperation107"),
            testData("Unsupported operation (108)", "unsupportedOperation108"),
            testData("Unsupported operation (109)", "unsupportedOperation109"),
            testData("Unsupported operation (110)", "unsupportedOperation110"),
            testData("Unsupported operation (111)", "unsupportedOperation111"),
            testData("Unsupported operation (112)", "unsupportedOperation112"),
            testData("Unsupported operation (113)", "unsupportedOperation113"),
            testData("Unsupported operation (114)", "unsupportedOperation114"),
            testData("Unsupported operation (115)", "unsupportedOperation115"),
            testData("Unsupported operation (116)", "unsupportedOperation116"),
            testData("Unsupported operation (117)", "unsupportedOperation117"),
            testData("Unsupported operation (118)", "unsupportedOperation118"),
            testData("Unsupported operation (119)", "unsupportedOperation119"),
            testData("Unsupported operation (120)", "unsupportedOperation120"),
            testData("Unsupported operation (121)", "unsupportedOperation121"),
            testData("Unsupported operation (122)", "unsupportedOperation122"),
            testData("Unsupported operation (123)", "unsupportedOperation123"),
            testData("Unsupported operation (124)", "unsupportedOperation124"),
            testData("Unsupported operation (125)", "unsupportedOperation125"),
            testData("Unsupported operation (126)", "unsupportedOperation126"),
            testData("Unsupported operation (127)", "unsupportedOperation127"),
            testData("Unsupported operation (128)", "unsupportedOperation128"),
            testData("Unsupported operation (129)", "unsupportedOperation129"),
            testData("Unsupported operation (130)", "unsupportedOperation130"),
            testData("Unsupported operation (131)", "unsupportedOperation131"),
            testData("Unsupported operation (132)", "unsupportedOperation132"),
            testData("Unsupported operation (133)", "unsupportedOperation133"),
            testData("Unsupported operation (134)", "unsupportedOperation134"),
            testData("Unsupported operation (135)", "unsupportedOperation135"),
            testData("Unsupported operation (136)", "unsupportedOperation136"),
            testData("Unsupported operation (137)", "unsupportedOperation137"),
            testData("Unsupported operation (138)", "unsupportedOperation138"),
            testData("Unsupported operation (139)", "unsupportedOperation139"),
            testData("Unsupported operation (140)", "unsupportedOperation140"),
            testData("Unsupported operation (141)", "unsupportedOperation141"),
            testData("Unsupported operation (142)", "unsupportedOperation142"),
            testData("Unsupported operation (143)", "unsupportedOperation143"),
            testData("Unsupported operation (144)", "unsupportedOperation144"),
            testData("Unsupported operation (145)", "unsupportedOperation145"),
            testData("Unsupported operation (146)", "unsupportedOperation146"),
            testData("Unsupported operation (147)", "unsupportedOperation147"),
            testData("Unsupported operation (148)", "unsupportedOperation148"),
            testData("Unsupported operation (149)", "unsupportedOperation149"),
            testData("Unsupported operation (150)", "unsupportedOperation150"),
            testData("Unsupported operation (151)", "unsupportedOperation151"),
            testData("Unsupported operation (152)", "unsupportedOperation152"),
            testData("Unsupported operation (153)", "unsupportedOperation153"),
            testData("Unsupported operation (154)", "unsupportedOperation154"),
            testData("Unsupported operation (155)", "unsupportedOperation155"),
            testData("Unsupported operation (156)", "unsupportedOperation156"),
            testData("Unsupported operation (157)", "unsupportedOperation157"),
            testData("Unsupported operation (158)", "unsupportedOperation158"),
            testData("Unsupported operation (159)", "unsupportedOperation159"),
            testData("Unsupported operation (160)", "unsupportedOperation160"),
            testData("Unsupported operation (161)", "unsupportedOperation161"),
            testData("Unsupported operation (162)", "unsupportedOperation162"),
            testData("Unsupported operation (163)", "unsupportedOperation163"),
            testData("Unsupported operation (164)", "unsupportedOperation164"),
            testData("Unsupported operation (165)", "unsupportedOperation165"),
            testData("Unsupported operation (166)", "unsupportedOperation166"),
            testData("Unsupported operation (167)", "unsupportedOperation167"),
            testData("Unsupported operation (168)", "unsupportedOperation168"),
            testData("Unsupported operation (169)", "unsupportedOperation169"),
            testData("Unsupported operation (170)", "unsupportedOperation170"),
            testData("Unsupported operation (171)", "unsupportedOperation171"),
            testData("Unsupported operation (172)", "unsupportedOperation172"),
            testData("Unsupported operation (173)", "unsupportedOperation173"),
            testData("Unsupported operation (174)", "unsupportedOperation174"),
            testData("Unsupported operation (175)", "unsupportedOperation175"),
            testData("Unsupported operation (176)", "unsupportedOperation176"),
            testData("Unsupported operation (177)", "unsupportedOperation177"),
            testData("Unsupported operation (178)", "unsupportedOperation178"),
            testData("Unsupported operation (179)", "unsupportedOperation179"),
            testData("Unsupported operation (180)", "unsupportedOperation180"),
            testData("Unsupported operation (181)", "unsupportedOperation181"),
            testData("Unsupported operation (182)", "unsupportedOperation182"),
            testData("Unsupported operation (183)", "unsupportedOperation183"),
            testData("Unsupported operation (184)", "unsupportedOperation184"),
            testData("Unsupported operation (185)", "unsupportedOperation185"),
            testData("Unsupported operation (186)", "unsupportedOperation186"),
            testData("Unsupported operation (187)", "unsupportedOperation187"),
            testData("Unsupported operation (188)", "unsupportedOperation188"),
            testData("Unsupported operation (189)", "unsupportedOperation189"),
            testData("Unsupported operation (190)", "unsupportedOperation190"),
            testData("Unsupported operation (191)", "unsupportedOperation191"),
            testData("Unsupported operation (192)", "unsupportedOperation192"),
            testData("Unsupported operation (193)", "unsupportedOperation193"),
            testData("Unsupported operation (194)", "unsupportedOperation194"),
            testData("Unsupported operation (195)", "unsupportedOperation195"),
            testData("Unsupported operation (196)", "unsupportedOperation196"),
            testData("Unsupported operation (197)", "unsupportedOperation197"),
            testData("Unsupported operation (198)", "unsupportedOperation198"),
            testData("The entity type is not an aggregate", "notAggregateEntityType"),
            testData("Duplicates of aliases", "duplicateAliases"),
            testData("Redundant fields during request merge", "extraFieldsForRequestsMerge"),
            testData("Insufficient number of requests for merging", "notEnoughRequestsForMerge"),
            testData("Properties type conflict", "propertiesTypeConflict"),
            testData("Conflict of property types (2)", "propertiesTypeConflict2"),
            testData("Conflict of property types (3)", "propertiesTypeConflict3"),
            testData("Type property conflict (4)", "propertiesTypeConflict4"),
            testData("Conflict of property types (5)", "propertiesTypeConflict5"),
            testData("Redundant fields during property selection", "extraFieldsForPropertiesSelection"),
            testData("No property selected", "noPropertySelected"),
            testData("The node is not a symbol", "notCharacterNode"),
            testData("The parameter value is not set", "paramValueNotSet"),
            testData("The parameter value is not set (2)", "paramValueNotSet2"),
            testData("Null value is set for parameter collection", "nullParamValueSetForCollection"),
            testData("Given a null value for the collection parameter (2)", "nullParamValueSetForCollection2"),
            testData("The types of array elements must be of the same type", "arrayElemTypesShouldBeOfOneType"));
    }
}
